### ISSUE TITLE
Serialization of 'Closure' is not allowed

### ISSUE THREAD

**Issue by thomas-alrek** [beyondcode/tinkerwell-helper#2]
Thank you for this cool helper. I was testing it out, and got the following error when testing.

```php
$test = function () {
    return true;
};

tinker($test);
```

Also, would it be possible to add support for ```tinker($this)``` when in a class context?

**Comment by mpociot** [comment]
Unfortunately, it is only possible to send data to tinkerwell that can be serialized - which is not easily possible with closures. When in a class context, it will work as long as the class itself can be serialized, even though I'm not sure about that, since it would have the variable name `$this` , which PHP might not like
